- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Copy nginx configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644

- name: Restart nginx
  service:
    name: nginx
    state: restarted