- name: Deploy Prometheus in Docker with Ansible
  hosts: Monitoring_host
  become: yes
  tasks:

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Pull Prometheus Docker image
      docker_image:
        name: prom/prometheus
        source: pull

    - name: Run Prometheus container
      docker_container:
        name: prometheus
        image: prom/prometheus
        state: started
        restart_policy: unless-stopped
        ports:
          - "9090:9090"