apiVersion: v2
name: webapp-chart
description: A Helm chart for web application deployment
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - webapp
  - nginx
  - kubernetes
maintainers:
  - name: DevOps Team
    email: devops@example.com
