---
- name: Update apt cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist
  tags: base

- name: Install common utilities
  apt:
    name:
      - curl
      - wget
      - vim
      - git
      - fail2ban
    state: present
  tags: base

- name: Enable and start fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
  tags: base