services:
  api:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/todoapp
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: