
version: 0.0
os: linux
files:
  - source: / # Source root of the artifact
    destination: /var/www/html/ # Destination on your EC2 instance (e.g., where Apache serves files)
permissions:
  - object: /var/www/html/
    pattern: "**"
    owner: apache # Or whatever user your web server runs as
    group: apache
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh # Optional: run a script before install
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh # Optional: run a script after install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh # Optional: restart web server
      timeout: 300
      runas: root