name: Build and Deploy Node Service

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/yourusername/node-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ env.IMAGE_NAME }}
            docker stop node-service || true
            docker rm node-service || true
            docker run -d --name node-service -p 80:3000 \
              -e SECRET_MESSAGE="${{ secrets.SECRET_MESSAGE }}" \
              -e USERNAME="${{ secrets.DEPLOY_USERNAME }}" \
              -e PASSWORD="${{ secrets.DEPLOY_PASSWORD }}" \
              ${{ env.IMAGE_NAME }}