apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guestbook-prod
resources:
- ../../base
patchesStrategicMerge:
- deployment-patch.yaml
- ingress.yaml
commonLabels:
  environment: production
images:
- name: gcr.io/heptio-images/ks-guestbook-demo
  newTag: "0.1"