- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential packages
  apt:
    name:
      - git
      - curl
      - ufw
    state: present

- name: Enable UFW firewall
  ufw:
    state: enabled
    policy: allow