name: CI/CD for Todo API

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: yourdockerhubusername/todo-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} ./app

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ env.IMAGE_NAME }}
            docker-compose -f /app/docker-compose.yml down
            docker-compose -f /app/docker-compose.yml up -d --build