global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['locahost:9100']
        # Use 'localhost' if running natively, or host.docker.internal for Docker
  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['localhost:9113']