apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
  namespace: argocd
  labels:
    environment: dev
spec:
  project: guestbook
  source:
    repoURL: https://github.com/your-username/gitops-demo
    targetRevision: HEAD
    path: appconfigs/guestbook/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m