apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-prod
  namespace: argocd
  labels:
    environment: production
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
spec:
  project: guestbook
  source:
    repoURL: https://github.com/your-username/gitops-demo
    targetRevision: release
    path: appconfigs/guestbook/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true