services:
  planet-service:
    build: ./planet-service
    ports:
      - "8000:8000"
    volumes:
      - ./shared:/app/shared
    environment:
      - JWT_SECRET_KEY=your-secret-key-here
    networks:
      - insecure-microservices

  salvation-service:
    build: ./salvation-service
    ports:
      - "8001:8001"
    volumes:
      - ./shared:/app/shared
    environment:
      - PLANET_SERVICE_URL=http://planet-service:8000
      - JWT_SECRET_KEY=your-secret-key-here
    networks:
      - insecure-microservices

  creation-service:
    build: ./creation-service
    ports:
      - "8002:8002"
    volumes:
      - ./shared:/app/shared
    environment:
      - PLANET_SERVICE_URL=http://planet-service:8000
      - JWT_SECRET_KEY=your-secret-key-here
    networks:
      - insecure-microservices

  auth-service:
    build: ./auth-service
    ports:
      - "8003:8003"
    volumes:
      - ./shared:/app/shared
    environment:
      - JWT_SECRET_KEY=your-secret-key-here
    networks:
      - insecure-microservices

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_PLANET_SERVICE_URL=http://localhost:8000
      - REACT_APP_CREATION_SERVICE_URL=http://localhost:8002
      - REACT_APP_SALVATION_SERVICE_URL=http://localhost:8001
      - REACT_APP_AUTH_SERVICE_URL=http://localhost:8003
    networks:
      - insecure-microservices

networks:
  insecure-microservices:
    driver: bridge 